status = warn
name = UaaLogging

appender.console.type = Console
appender.console.name = CONSOLE
appender.console.target = SYSTEM_OUT

appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%t] %c{1.} - %m%n

rootLogger.level = INFO
rootLogger.appenderRef.console.ref = CONSOLE

logger.uaa.name = org.cloudfoundry.identity
logger.uaa.level = INFO

logger.spring.name = org.springframework
logger.spring.level = INFO