spring.application.name=spring-boot-kaizen
# spring.main.lazy-initialization=true/false
# spring.main.banner-mode=log/console/off
spring.threads.virtual.enabled=true

servlet.max-users=200
servlet.mode=production
notification.service.enable=true
app.service.name=A

#spring.task.execution.pool.max-size=16
#spring.task.execution.pool.queue-capacity=100
#spring.task.execution.pool.keep-alive=10s
#spring.task.execution.mode=force
#spring.task.execution.simple.concurrency-limit=10
#spring.task.scheduling.thread-name-prefix=scheduling-
#spring.task.scheduling.pool.size=2
#spring.main.allow-bean-definition-overriding=true
app.config.name= hi
app.config.port=80