spring.application.name=spring-security-jwt-login


spring.security.user.name=user
spring.security.user.password=password


jwt.secret=VvfuX9GNEeAg+VToAsG4cBPKyZkWTDZ3SnmMKjXyXmI=
jwt.access-token.expiration=900000
jwt.refresh-token.expiration=604800000