spring.application.name=spring-security-login


spring.security.user.name=admin
spring.security.user.password=admin



jwt.secret=VvfuX9GNEeAg+VToAsG4cBPKyZkWTDZ3SnmMKjXyXmI=
jwt.accessToken.expiration=900000
